trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: |
        **/*.yml
        **/*.tf
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - bash: ls -R $(Build.ArtifactStagingDirectory)
