trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: DeployToDev
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to Dev
- stage: QADeploy
  jobs:
  - deployment: DeployToQA
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to QA
