trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Pipelines > Stages > Jobs > Tasks(Steps)

jobs:
- job: Job1
  steps:
  - script: echo Job1!
    displayName: 'Run a one-line script'
- job: Job2
  steps:
  - script: echo Job2!
    displayName: 'Run a one-line script'
- job: Job3
  steps:
  - script: echo Job3!
    displayName: 'Run a one-line script'
